### ISSUE TITLE
Deploy command taking 16 minutes to deploy to Azure App service

### ISSUE THREAD

**Issue by kunjneo** [OfficeDev/teamsfx-cli-action#25]
Hi Team,

We are using OfficeDev/teamsfx-cli-action@v1 with commands as deploy to deploy the app service in our dev and production Azure environment using github action but the deploy command is taking around 16 minutes

It would be great if someone can help with the issue

![image](https://github.com/OfficeDev/teamsfx-cli-action/assets/142484309/85e7b600-7435-498f-9b00-d584440c17d6)

**Comment by yukun-dong** [comment]
Hi @kunjneo , you can follow this guide https://github.com/OfficeDev/TeamsFx/wiki/How-to-configure-WEBSITE_RUN_FROM_PACKAGE-in-Azure-App-Service to enable RUN FROM PACKAGE for your app service. This could make the deploy time shorter.

I will close this issue since this GitHub Action is no longer being maintained. If you have further questions please raise issue here: https://github.com/OfficeDev/TeamsFx/issues
